### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by bawilc01** [paulbarrera/OnlineForm_TheGame#1]
There is a comma missing after one of the questions. Also, an error will be thrown when showing the final score because the print statements don't support integer values, only strings. So, score will have to be converted to an int. Will attempt to submit a pull request for the issue with the updated code for you to review.

**Comment by bawilc01** [comment]
forked project; made changes; and submitted pull request for Paul to review and possibly merge to his master branch

**Comment by paulbarrera** [comment]
Reviewed the updated code and made the necessary corrections. Added the missing comma to the question and changed the last function to a string. Made the pull request to the local machine.
